### DISCUSSION TITLE
CodeBlock can't copy the code

### DISCUSSION THREAD

**Discussion by Dumbliidore** [rio-labs/rio#252] [Q&A]
System: Windows11
python version: python3.11

```toml
# This is the configuration file for Rio, an easy to use app & web framework for
# Python.

[app]
# This is either "website" or "app"
app-type = "app"

# The name of your Python module
main-module = "rio_test"

# All files which are part of your project. Changes to these will trigger a
# reload and they will be packed up when deploying.
project-files = ["*.py", "/assets/", "/rio.toml"]
```

```python
from __future__ import annotations

import rio


class Output(rio.Component):
    def build(self) -> rio.Component:
        text = "This is a text code."
        return rio.Column(
            rio.Text(
                text="Output",
                style=rio.TextStyle(
                    font=rio.text_style.Font.ROBOTO, font_size=1.2, font_weight="bold"
                ),
                margin_left=0.3,
            ),
            # rio.MultiLineTextInput(text=text),
            rio.CodeBlock(text, language="bash", min_height=6),
            spacing=0.5,
            margin_bottom=0.5,
        )
```

![image](https://github.com/user-attachments/assets/08840c16-5d5f-487f-ba72-8dee8fcf3451)

I click the button to copy the code to the clipboard, but it doesn't work.
